project_id = "csupviqxprhtrbfbugct"

[functions.relationship-ai]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.create-admin-user]
verify_jwt = false

[functions.daily-question-notification]
verify_jwt = false

[functions.admin-stats]
verify_jwt = true

[functions.update-user-password]
verify_jwt = false

[functions.admin-metrics]
verify_jwt = true

[functions.presence-heartbeat]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false