// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csupviqxprhtrbfbugct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzdXB2aXF4cHJodHJiZmJ1Z2N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjkzMDAsImV4cCI6MjA2OTA0NTMwMH0.n6TVqq3meOhshgGzTfMt2Ef90mSYi8mxUz2UXteyHzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});